import { useAuth } from "@/hooks";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  /**
   * page states
   */
  const { user } = useAuth();
  console.log("user", user);

  /**
   * page functions
   */

  return (
    <>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="themeBorder flex h-full items-center justify-center  border border-primary/50">
        {user?.role === "admin" ? (
          <p className="text-center text-xl font-bold text-primary">
            Easy and faster student management. <br /> Let&apos;s make it work.
          </p>
        ) : (
          <p className="text-center text-xl font-bold text-primary">
            Putting Your Child&apos;s Future <br /> in Great Motion
          </p>
        )}
      </main>
    </>
  );
};

export default Home;
